// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1) {
  return window['go']['app']['App']['CloseSession'](arg1);
}

export function CloseTerminal(arg1) {
  return window['go']['app']['App']['CloseTerminal'](arg1);
}

export function Connect(arg1) {
  return window['go']['app']['App']['Connect'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['app']['App']['DeleteConnection'](arg1);
}

export function ListConnections() {
  return window['go']['app']['App']['ListConnections']();
}

export function LogError(arg1) {
  return window['go']['app']['App']['LogError'](arg1);
}

export function LogPath() {
  return window['go']['app']['App']['LogPath']();
}

export function MaybeCloseSession(arg1) {
  return window['go']['app']['App']['MaybeCloseSession'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['app']['App']['OpenFileDialog'](arg1);
}

export function OpenTerminal(arg1, arg2, arg3) {
  return window['go']['app']['App']['OpenTerminal'](arg1, arg2, arg3);
}

export function ReadLocalFile(arg1) {
  return window['go']['app']['App']['ReadLocalFile'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveConnection(arg1) {
  return window['go']['app']['App']['SaveConnection'](arg1);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['app']['App']['SaveFileDialog'](arg1, arg2);
}

export function SftpDelete(arg1, arg2, arg3) {
  return window['go']['app']['App']['SftpDelete'](arg1, arg2, arg3);
}

export function SftpDownload(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SftpDownload'](arg1, arg2, arg3, arg4);
}

export function SftpList(arg1, arg2) {
  return window['go']['app']['App']['SftpList'](arg1, arg2);
}

export function SftpMkdir(arg1, arg2) {
  return window['go']['app']['App']['SftpMkdir'](arg1, arg2);
}

export function SftpRename(arg1, arg2, arg3) {
  return window['go']['app']['App']['SftpRename'](arg1, arg2, arg3);
}

export function SftpUpload(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SftpUpload'](arg1, arg2, arg3, arg4);
}

export function SftpUploadLocalFile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SftpUploadLocalFile'](arg1, arg2, arg3, arg4);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['app']['App']['WriteTerminal'](arg1, arg2);
}
