// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function Connect(arg1:app.ConnectionConfig):Promise<string>;

export function DeleteConnection(arg1:string):Promise<void>;

export function ListConnections():Promise<Array<app.ConnectionConfig>>;

export function LogError(arg1:string):Promise<void>;

export function LogPath():Promise<string>;

export function MaybeCloseSession(arg1:string):Promise<boolean>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function OpenTerminal(arg1:string,arg2:number,arg3:number):Promise<string>;

export function ReadLocalFile(arg1:string):Promise<string>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveConnection(arg1:app.ConnectionConfig):Promise<string>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<string>;

export function SftpDelete(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SftpDownload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<number>;

export function SftpList(arg1:string,arg2:string):Promise<Array<app.FileEntry>>;

export function SftpMkdir(arg1:string,arg2:string):Promise<void>;

export function SftpRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpUpload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<number>;

export function SftpUploadLocalFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<number>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
